apiVersion: v1
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: wally-test
- name: HOST
  displayName: Host
  description: The hostname to deploy this template to.
  required: true
  value: wally-test.pathfinder.gov.bc.ca
- name: NAMESPACE
  displayName: Namespace
  description: The namespace to apply this template to.
  required: true
  value: d1b5d2-test
- name: REPLICAS
  value: '1'
objects:
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: wally-${NAME}
        env: ${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: wally-${NAME}
        env: ${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      name: wally-${NAME}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 10
      selector:
        app: wally-${NAME}
        env: ${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
            prometheus.io/scrape: 'true'
            prometheus.io/port: '4040'
          creationTimestamp: null
          labels:
            app: wally-${NAME}
            env: ${NAME}
            component: frontend
            name: wally-${NAME}-frontend
        spec:
          volumes:
          - name: shared-data
            emptyDir: {}
          containers:
            - image: quay.io/martinhelmich/prometheus-nginxlog-exporter
              name: nginx-log-exporter
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /metrics
                  port: 4040
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /metrics
                  port: 4040
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 50m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              ports:
                - containerPort: 4040
                  protocol: TCP
              volumeMounts:
              - name: shared-data
                mountPath: /var/opt/rh/rh-nginx112/log/nginx/
              # args:
              # - '-format="$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" rt=$request_time uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\" urt=\"$upstream_response_time\""'
              # - '-listen-port=4040'
              # - '-namespace=nginx'
              # - '/var/opt/rh/rh-nginx112/log/nginx/access.log'
            - image: >-
                image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/wally-web:${NAME}
              imagePullPolicy: Always
              name: wally
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              env:
              - name: WALLY_BACKEND_SERVICE
                value: wally-${NAME}-api
              volumeMounts:
              - name: shared-data
                mountPath: /var/opt/rh/rh-nginx112/log/nginx/
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - wally
            from:
              kind: ImageStreamTag
              name: wally-web:${NAME}
              namespace: ${NAMESPACE}
          type: ImageChange
        - type: ConfigChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      generation: 18
      labels:
        app: wally-${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      name: wally-${NAME}-frontend
kind: Template
metadata:
  resourceVersion: ''
  selfLink: ''
  labels:
    app: wally-${NAME}
    env: ${NAME}
    component: frontend
    name: wally-${NAME}-frontend
