apiVersion: v1
kind: Template
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: test
- name: GIT_REPO
  displayName: Git Repo URL
  description: The URL to your Git repo.
  required: true
  value: https://github.com/bcgov-c/wally.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: master
metadata:
  name: wally-frontend-build-template
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 900
      output:
        to:
          kind: ImageStreamTag
          name: wally-web:${NAME}
      postCommit: {}
      resources:
        limits:
          cpu: '4'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 2Gi
      runPolicy: SerialLatestOnly
      source:
        contextDir: frontend
        git:
          ref: "${GIT_REF}"
          uri: "${GIT_REPO}"
        sourceSecret:
          name: wally-github-token
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile.ocp4
          from:
            kind: ImageStreamTag
            name: 'nginx:1.16'
            namespace: openshift
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers:
        - type: ConfigChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        component: frontend
        name: wally-${NAME}-web
        app: wally-${NAME}
        env: "${NAME}"
      name: wally-${NAME}-web
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      generation: 3
      labels:
        component: frontend
        name: wally-web
        env: tools
      name: wally-web
