version: '3.3'
services:
  backend:
    build:
      context: ./backend
      args:
        env: dev
    networks:
      default:
        aliases:
          - ${DOMAIN}
    command: /app/start-reload.sh
    volumes:
      - ./backend:/app
    env_file:
      - env-postgres.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=http://${DOMAIN}
      - PORT=8000
    ports:
      - '8000:8000'
    depends_on:
      - db
  reporting:
    build:
      context: ./reporting
    # volumes:
    #   - ./reporting:/app
    env_file:
      - env-postgres.env
    depends_on:
      - db
      - backend
    ports:
      - '3000:3000'
  db:
    image: mdillon/postgis:11
    env_file:
      - env-postgres.env
    volumes:
      - ./.tmp/postgis-dev:/var/lib/postgresql/dat
    ports:
      - '5432:5432'
