version: '3.3'
services:
  backend:
    build:
      context: ./backend
      args:
        env: dev
    networks:
      default:
        aliases:
          - ${DOMAIN}
    command: /app/start-reload.sh
    volumes:
      - ./backend:/app
    env_file:
      - env-postgres.env
      - env-backend.env
    environment:
      PORT: 8000
      MAPBOX_ACCESS_TOKEN: "${MAPBOX_ACCESS_TOKEN}"
    ports:
      - '8000:8000'
    depends_on: 
      - db
  reporting:
    build:
      context: ./reporting
    # volumes:
    #   - ./reporting:/app
    environment:
      MAPBOX_ACCESS_TOKEN: "${MAPBOX_ACCESS_TOKEN}"
    env_file:
      - env-postgres.env
      - env-backend.env
    depends_on:
      - db
    ports:
      - '3000:3000'
  db:
    image: mdillon/postgis:11
    env_file:
      - env-postgres.env
    volumes:
      - ./.tmp/postgis-dev:/var/lib/postgresql/dat
    ports:
      - '5432:5432'
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.development
    depends_on:
      - backend
    ports:
      - '8080:8080'
    
