apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wally-importer-hydat
parameters:
- description: Environment name (staging or production)
  displayName: Environment name
  name: ENV_NAME
  value: staging
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: wally-importer-hydat
      labels:
        component: importer
        job: import-hydat
        name: wally-importer-hydat
    spec:
      parallelism: 1    
      completions: 1    
      template:         
        metadata:
          name: wally-importer-hydat
        spec:
          containers:
          - name: importer
            image: image-registry.openshift-image-registry.svc:5000/d1b5d2-tools/wally-importer:latest
            command: ['/dataload/load_hydat.sh']
            resources:
              requests:
                cpu: 200m
                memory: 4Gi
              limits:
                cpu: '1'
                memory: 4Gi
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: app-db-username
                  name: wally-psql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: app-db-password
                  name: wally-psql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: app-db-name
                  name: wally-psql
            - name: POSTGRES_SERVER
              value: wally-psql-${ENV_NAME}
          restartPolicy: Never
