apiVersion: v1
data:
  prod.env: |
    external_import=false
    external_import_types=
    wally_model=false
  staging.env: |
    external_import=false
    external_import_types=
    wally_model=true
  dev.env: |
    external_import=true
    external_import_types=csv, kml, geojson
    wally_model=true
kind: ConfigMap
metadata:
  name: wally-config
