apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wally-importer-job
parameters:
- description: Environment name (staging or production)
  displayName: Environment name
  name: ENV_NAME
  value: staging
- description: Map layer name.  A layer_name.zip and layer_name DB table should be available.
  displayName: Layer name
  name: LAYER_NAME
  required: true
- description: Job name. OpenShift jobs cannot have underscores, which most of our layers have.
  displayName: Job name
  name: JOB_NAME
  required: true
  value: dataload
- description: Sort key. DataBC WFS server does not allow pagination without a sort key.
  displayName: Sort key
  name: SORT_KEY
  required: true
- description: DataBC catalogue item name, e.g. WHSE_WATER_MANAGEMENT.WLS_WATER_RIGHTS_LICENCES_SV.
  displayName: DataBC catalogue item
  name: DATABC_NAME
  required: true
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: wally-download-${JOB_NAME}
      labels:
        component: importer
        job: download-${JOB_NAME}
        name: wally-download-${JOB_NAME}
    spec:
      backoffLimit: 3
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: wally-download-${JOB_NAME}
        spec:
          containers:
          - name: importer
            image: docker-registry.default.svc:5000/bfpeyx-tools/wally-importer:latest
            command: ['/dataload/wfs_direct_download.sh']
            args: ['${DATABC_NAME}', '${SORT_KEY}', '${LAYER_NAME}']
            resources:
              requests:
                cpu: 200m
                memory: 4Gi
              limits:
                cpu: '1'
                memory: 4Gi
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: app-db-username
                  name: wally-psql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: app-db-password
                  name: wally-psql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: app-db-name
                  name: wally-psql
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: minioAccessKey
                  name: minio
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: minioSecretKey
                  name: minio
            - name: POSTGRES_SERVER
              value: wally-psql-master-${ENV_NAME}
          restartPolicy: Never
