apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      Patroni Postgresql database cluster, with persistent storage.
    iconClass: icon-postgresql
    openshift.io/display-name: Patroni Postgresql (Persistent)
    openshift.io/long-description: This template deploys a patroni postgresql HA
      cluster with persistent storage.
    tags: postgresql
  name: patroni-pgsql-persistent-sa
labels:
  app: wally${SUFFIX}
  instance: ${NAME}${SUFFIX}
  component: database
  name: ${NAME}${SUFFIX}
  version: "10"
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      cluster-name: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      cluster-name: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
    - delete
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
    - delete
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
    - patch
    - update
    - create
    - list
    - watch
    - delete
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      cluster-name: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ${NAME}${SUFFIX}
  subjects:
  - kind: ServiceAccount
    name: ${NAME}${SUFFIX}
parameters:
- description: The name of the application for labelling all artifacts.
  displayName: Application Name
  name: NAME
  value: wally-psql
- name: SUFFIX
  description: A suffix appended to all artifact's name (NAME)
