apiVersion: v1
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: wally-test
- name: HOST
  displayName: Host
  description: The hostname to deploy this template to.
  required: true
  value: wally-test.pathfinder.gov.bc.ca
- name: NAMESPACE
  displayName: Namespace
  description: The namespace to apply this template to.
  required: true
  value: bfpeyx-test
- name: REPLICAS
  value: 1
objects:
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: wally-${NAME}
        env: ${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: wally-${NAME}
        env: ${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      name: wally-${NAME}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: ${REPLICAS}
      revisionHistoryLimit: 10
      selector:
        app: wally-${NAME}
        env: ${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: wally-${NAME}
            env: ${NAME}
            component: frontend
            name: wally-${NAME}-frontend
        spec:
          containers:
            - image: >-
                docker-registry.default.svc:5000/${NAMESPACE}/wally-web:${NAME}
              imagePullPolicy: Always
              name: wally
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              env:
              - name: WALLY_BACKEND_SERVICE
                value: wally-${NAME}-api
              - name: WALLY_REPORTING_SERVICE
                value: wally-${NAME}-reporting
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - wally
            from:
              kind: ImageStreamTag
              name: wally-web:${NAME}
              namespace: ${NAMESPACE}
          type: ImageChange
        - type: ConfigChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      generation: 18
      labels:
        app: wally-${NAME}
        component: frontend
        name: wally-${NAME}-frontend
      name: wally-${NAME}-frontend
kind: Template
metadata:
  resourceVersion: ''
  selfLink: ''
  labels:
    app: wally-${NAME}
    env: ${NAME}
    component: frontend
    name: wally-${NAME}-frontend
